# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/bd_fpga/bd_fpga.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fpga || ORIG_REF_NAME==bd_fpga} -quiet] -quiet

# IP: bd/bd_fpga/ip/bd_fpga_processing_system7_0_0/bd_fpga_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fpga_processing_system7_0_0 || ORIG_REF_NAME==bd_fpga_processing_system7_0_0} -quiet] -quiet

# IP: bd/bd_fpga/ip/bd_fpga_floating_point_0_0/bd_fpga_floating_point_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fpga_floating_point_0_0 || ORIG_REF_NAME==bd_fpga_floating_point_0_0} -quiet] -quiet

# IP: bd/bd_fpga/ip/bd_fpga_axi_dma_0_0/bd_fpga_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fpga_axi_dma_0_0 || ORIG_REF_NAME==bd_fpga_axi_dma_0_0} -quiet] -quiet

# IP: bd/bd_fpga/ip/bd_fpga_ps7_0_axi_periph_0/bd_fpga_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fpga_ps7_0_axi_periph_0 || ORIG_REF_NAME==bd_fpga_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/bd_fpga/ip/bd_fpga_rst_ps7_0_100M_0/bd_fpga_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fpga_rst_ps7_0_100M_0 || ORIG_REF_NAME==bd_fpga_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/bd_fpga/ip/bd_fpga_smartconnect_0_0/bd_fpga_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fpga_smartconnect_0_0 || ORIG_REF_NAME==bd_fpga_smartconnect_0_0} -quiet] -quiet

# IP: bd/bd_fpga/ip/bd_fpga_system_ila_0_0/bd_fpga_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fpga_system_ila_0_0 || ORIG_REF_NAME==bd_fpga_system_ila_0_0} -quiet] -quiet

# IP: bd/bd_fpga/ip/bd_fpga_floating_point_2_0/bd_fpga_floating_point_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fpga_floating_point_2_0 || ORIG_REF_NAME==bd_fpga_floating_point_2_0} -quiet] -quiet

# IP: bd/bd_fpga/ip/bd_fpga_axis_dot_20_10_0_0/bd_fpga_axis_dot_20_10_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fpga_axis_dot_20_10_0_0 || ORIG_REF_NAME==bd_fpga_axis_dot_20_10_0_0} -quiet] -quiet

# IP: bd/bd_fpga/ip/bd_fpga_axis_bias_10_0_0/bd_fpga_axis_bias_10_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fpga_axis_bias_10_0_0 || ORIG_REF_NAME==bd_fpga_axis_bias_10_0_0} -quiet] -quiet

# IP: bd/bd_fpga/ip/bd_fpga_floating_point_1_0/bd_fpga_floating_point_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fpga_floating_point_1_0 || ORIG_REF_NAME==bd_fpga_floating_point_1_0} -quiet] -quiet

# IP: bd/bd_fpga/ip/bd_fpga_axis_tanh_10_0_0/bd_fpga_axis_tanh_10_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fpga_axis_tanh_10_0_0 || ORIG_REF_NAME==bd_fpga_axis_tanh_10_0_0} -quiet] -quiet

# IP: bd/bd_fpga/ip/bd_fpga_axis_dot_80_40_0_0/bd_fpga_axis_dot_80_40_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fpga_axis_dot_80_40_0_0 || ORIG_REF_NAME==bd_fpga_axis_dot_80_40_0_0} -quiet] -quiet

# IP: bd/bd_fpga/ip/bd_fpga_floating_point_0_1/bd_fpga_floating_point_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fpga_floating_point_0_1 || ORIG_REF_NAME==bd_fpga_floating_point_0_1} -quiet] -quiet

# IP: bd/bd_fpga/ip/bd_fpga_axis_bias_40_0_0/bd_fpga_axis_bias_40_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fpga_axis_bias_40_0_0 || ORIG_REF_NAME==bd_fpga_axis_bias_40_0_0} -quiet] -quiet

# IP: bd/bd_fpga/ip/bd_fpga_floating_point_2_1/bd_fpga_floating_point_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fpga_floating_point_2_1 || ORIG_REF_NAME==bd_fpga_floating_point_2_1} -quiet] -quiet

# IP: bd/bd_fpga/ip/bd_fpga_floating_point_1_1/bd_fpga_floating_point_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fpga_floating_point_1_1 || ORIG_REF_NAME==bd_fpga_floating_point_1_1} -quiet] -quiet

# IP: bd/bd_fpga/ip/bd_fpga_axis_tanh_40_0_0/bd_fpga_axis_tanh_40_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fpga_axis_tanh_40_0_0 || ORIG_REF_NAME==bd_fpga_axis_tanh_40_0_0} -quiet] -quiet

# IP: bd/bd_fpga/ip/bd_fpga_axis_dot_40_20_0_0/bd_fpga_axis_dot_40_20_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fpga_axis_dot_40_20_0_0 || ORIG_REF_NAME==bd_fpga_axis_dot_40_20_0_0} -quiet] -quiet

# IP: bd/bd_fpga/ip/bd_fpga_floating_point_3_0/bd_fpga_floating_point_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fpga_floating_point_3_0 || ORIG_REF_NAME==bd_fpga_floating_point_3_0} -quiet] -quiet

# IP: bd/bd_fpga/ip/bd_fpga_floating_point_4_0/bd_fpga_floating_point_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fpga_floating_point_4_0 || ORIG_REF_NAME==bd_fpga_floating_point_4_0} -quiet] -quiet

# IP: bd/bd_fpga/ip/bd_fpga_floating_point_5_0/bd_fpga_floating_point_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fpga_floating_point_5_0 || ORIG_REF_NAME==bd_fpga_floating_point_5_0} -quiet] -quiet

# IP: bd/bd_fpga/ip/bd_fpga_axis_bias_20_0_0/bd_fpga_axis_bias_20_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fpga_axis_bias_20_0_0 || ORIG_REF_NAME==bd_fpga_axis_bias_20_0_0} -quiet] -quiet

# IP: bd/bd_fpga/ip/bd_fpga_axis_tanh_20_0_0/bd_fpga_axis_tanh_20_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fpga_axis_tanh_20_0_0 || ORIG_REF_NAME==bd_fpga_axis_tanh_20_0_0} -quiet] -quiet

# IP: bd/bd_fpga/ip/bd_fpga_actual_axis_dot_20_10_0_1/bd_fpga_actual_axis_dot_20_10_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fpga_actual_axis_dot_20_10_0_1 || ORIG_REF_NAME==bd_fpga_actual_axis_dot_20_10_0_1} -quiet] -quiet

# IP: bd/bd_fpga/ip/bd_fpga_actual_axis_bias_10_0_0/bd_fpga_actual_axis_bias_10_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fpga_actual_axis_bias_10_0_0 || ORIG_REF_NAME==bd_fpga_actual_axis_bias_10_0_0} -quiet] -quiet

# IP: bd/bd_fpga/ip/bd_fpga_floating_point_6_1/bd_fpga_floating_point_6_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fpga_floating_point_6_1 || ORIG_REF_NAME==bd_fpga_floating_point_6_1} -quiet] -quiet

# IP: bd/bd_fpga/ip/bd_fpga_floating_point_7_0/bd_fpga_floating_point_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fpga_floating_point_7_0 || ORIG_REF_NAME==bd_fpga_floating_point_7_0} -quiet] -quiet

# IP: bd/bd_fpga/ip/bd_fpga_auto_pc_0/bd_fpga_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fpga_auto_pc_0 || ORIG_REF_NAME==bd_fpga_auto_pc_0} -quiet] -quiet

# XDC: bd/bd_fpga/bd_fpga_ooc.xdc
