


///////////////////////////////////////////////////////////////////////////
//NOTE: This file has been automatically generated by Vivado.
///////////////////////////////////////////////////////////////////////////
`timescale 1ps/1ps
package bd_axis_tanh_axi4stream_vip_0_0_pkg;
import axi4stream_vip_pkg::*;
///////////////////////////////////////////////////////////////////////////
// These parameters are named after the component for use in your verification 
// environment.
///////////////////////////////////////////////////////////////////////////
      parameter bd_axis_tanh_axi4stream_vip_0_0_VIP_INTERFACE_MODE     = 0;
      parameter bd_axis_tanh_axi4stream_vip_0_0_VIP_SIGNAL_SET         = 8'b00000011;
      parameter bd_axis_tanh_axi4stream_vip_0_0_VIP_DATA_WIDTH         = 32;
      parameter bd_axis_tanh_axi4stream_vip_0_0_VIP_ID_WIDTH           = 0;
      parameter bd_axis_tanh_axi4stream_vip_0_0_VIP_DEST_WIDTH         = 0;
      parameter bd_axis_tanh_axi4stream_vip_0_0_VIP_USER_WIDTH         = 0;
      parameter bd_axis_tanh_axi4stream_vip_0_0_VIP_USER_BITS_PER_BYTE = 0;
      parameter bd_axis_tanh_axi4stream_vip_0_0_VIP_HAS_TREADY         = 1;
      parameter bd_axis_tanh_axi4stream_vip_0_0_VIP_HAS_TSTRB          = 0;
      parameter bd_axis_tanh_axi4stream_vip_0_0_VIP_HAS_TKEEP          = 0;
      parameter bd_axis_tanh_axi4stream_vip_0_0_VIP_HAS_TLAST          = 0;
      parameter bd_axis_tanh_axi4stream_vip_0_0_VIP_HAS_ACLKEN         = 0;
      parameter bd_axis_tanh_axi4stream_vip_0_0_VIP_HAS_ARESETN        = 1;
///////////////////////////////////////////////////////////////////////////
typedef axi4stream_mst_agent #(bd_axis_tanh_axi4stream_vip_0_0_VIP_SIGNAL_SET, 
                        bd_axis_tanh_axi4stream_vip_0_0_VIP_DEST_WIDTH,
                        bd_axis_tanh_axi4stream_vip_0_0_VIP_DATA_WIDTH,
                        bd_axis_tanh_axi4stream_vip_0_0_VIP_ID_WIDTH,
                        bd_axis_tanh_axi4stream_vip_0_0_VIP_USER_WIDTH, 
                        bd_axis_tanh_axi4stream_vip_0_0_VIP_USER_BITS_PER_BYTE,
                        bd_axis_tanh_axi4stream_vip_0_0_VIP_HAS_ARESETN) bd_axis_tanh_axi4stream_vip_0_0_mst_t;
      
///////////////////////////////////////////////////////////////////////////
// How to start the verification component
///////////////////////////////////////////////////////////////////////////
//      bd_axis_tanh_axi4stream_vip_0_0_mst_t  bd_axis_tanh_axi4stream_vip_0_0_mst;
//      initial begin : START_bd_axis_tanh_axi4stream_vip_0_0_MASTER
//        bd_axis_tanh_axi4stream_vip_0_0_mst = new("bd_axis_tanh_axi4stream_vip_0_0_mst", `bd_axis_tanh_axi4stream_vip_0_0_PATH_TO_INTERFACE);
//        bd_axis_tanh_axi4stream_vip_0_0_mst.start_master();
//      end



endpackage : bd_axis_tanh_axi4stream_vip_0_0_pkg
