


///////////////////////////////////////////////////////////////////////////
//NOTE: This file has been automatically generated by Vivado.
///////////////////////////////////////////////////////////////////////////
`timescale 1ps/1ps
package bd_last_layer_axi4stream_vip_0_1_pkg;
import axi4stream_vip_pkg::*;
///////////////////////////////////////////////////////////////////////////
// These parameters are named after the component for use in your verification 
// environment.
///////////////////////////////////////////////////////////////////////////
      parameter bd_last_layer_axi4stream_vip_0_1_VIP_INTERFACE_MODE     = 2;
      parameter bd_last_layer_axi4stream_vip_0_1_VIP_SIGNAL_SET         = 8'b00011011;
      parameter bd_last_layer_axi4stream_vip_0_1_VIP_DATA_WIDTH         = 32;
      parameter bd_last_layer_axi4stream_vip_0_1_VIP_ID_WIDTH           = 0;
      parameter bd_last_layer_axi4stream_vip_0_1_VIP_DEST_WIDTH         = 0;
      parameter bd_last_layer_axi4stream_vip_0_1_VIP_USER_WIDTH         = 0;
      parameter bd_last_layer_axi4stream_vip_0_1_VIP_USER_BITS_PER_BYTE = 0;
      parameter bd_last_layer_axi4stream_vip_0_1_VIP_HAS_TREADY         = 1;
      parameter bd_last_layer_axi4stream_vip_0_1_VIP_HAS_TSTRB          = 0;
      parameter bd_last_layer_axi4stream_vip_0_1_VIP_HAS_TKEEP          = 1;
      parameter bd_last_layer_axi4stream_vip_0_1_VIP_HAS_TLAST          = 1;
      parameter bd_last_layer_axi4stream_vip_0_1_VIP_HAS_ACLKEN         = 0;
      parameter bd_last_layer_axi4stream_vip_0_1_VIP_HAS_ARESETN        = 1;
///////////////////////////////////////////////////////////////////////////


typedef axi4stream_slv_agent #(bd_last_layer_axi4stream_vip_0_1_VIP_SIGNAL_SET, 
                        bd_last_layer_axi4stream_vip_0_1_VIP_DEST_WIDTH,
                        bd_last_layer_axi4stream_vip_0_1_VIP_DATA_WIDTH,
                        bd_last_layer_axi4stream_vip_0_1_VIP_ID_WIDTH,
                        bd_last_layer_axi4stream_vip_0_1_VIP_USER_WIDTH, 
                        bd_last_layer_axi4stream_vip_0_1_VIP_USER_BITS_PER_BYTE,
                        bd_last_layer_axi4stream_vip_0_1_VIP_HAS_ARESETN) bd_last_layer_axi4stream_vip_0_1_slv_t;
      
///////////////////////////////////////////////////////////////////////////
// How to start the verification component
///////////////////////////////////////////////////////////////////////////
//      bd_last_layer_axi4stream_vip_0_1_slv_t  bd_last_layer_axi4stream_vip_0_1_slv;
//      initial begin : START_bd_last_layer_axi4stream_vip_0_1_SLAVE
//        bd_last_layer_axi4stream_vip_0_1_slv = new("bd_last_layer_axi4stream_vip_0_1_slv", `bd_last_layer_axi4stream_vip_0_1_PATH_TO_INTERFACE);
//        bd_last_layer_axi4stream_vip_0_1_slv.start_slave();
//      end

endpackage : bd_last_layer_axi4stream_vip_0_1_pkg
