# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lukefahr/e315/project_x/project_x.srcs/sources_1/bd/bd_fpga/ip/bd_fpga_processing_system7_0_0/bd_fpga_processing_system7_0_0.xci
# IP: The module: 'bd_fpga_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lukefahr/e315/project_x/project_x.srcs/sources_1/bd/bd_fpga/ip/bd_fpga_processing_system7_0_0/bd_fpga_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_fpga_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/lukefahr/e315/project_x/project_x.srcs/sources_1/bd/bd_fpga/ip/bd_fpga_processing_system7_0_0/bd_fpga_processing_system7_0_0.xci
# IP: The module: 'bd_fpga_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lukefahr/e315/project_x/project_x.srcs/sources_1/bd/bd_fpga/ip/bd_fpga_processing_system7_0_0/bd_fpga_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_fpga_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
