@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.3 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun May 03 12:38:50 -0400 2020
REM SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim tb_last_layer_behav -key {Behavioral:sim_last_layer:Functional:tb_last_layer} -tclbatch tb_last_layer.tcl -protoinst "protoinst_files/bd_c6eb.protoinst" -protoinst "protoinst_files/bd_5efb.protoinst" -protoinst "protoinst_files/bd_fpga.protoinst" -protoinst "protoinst_files/bd_0c8f.protoinst" -protoinst "protoinst_files/bd_4677.protoinst" -protoinst "protoinst_files/bd_fpga_test.protoinst" -protoinst "protoinst_files/bd_axis_tanh.protoinst" -protoinst "protoinst_files/bd_dot.protoinst" -protoinst "protoinst_files/bd_layer.protoinst" -protoinst "protoinst_files/bd_bias_layer.protoinst" -protoinst "protoinst_files/bd_last_layer.protoinst" -view C:/Users/Tyler/Documents/GitHub/E315_Final/vivado_project/project_x_V5/tb_last_layer_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
