#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.3 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Apr 28 08:19:17 PDT 2020
# SW Build 2405991 on Thu Dec  6 23:36:41 MST 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim tb_last_layer_behav -key {Behavioral:sim_last_layer:Functional:tb_last_layer} -tclbatch tb_last_layer.tcl -protoinst "protoinst_files/bd_c6eb.protoinst" -protoinst "protoinst_files/bd_5efb.protoinst" -protoinst "protoinst_files/bd_fpga.protoinst" -protoinst "protoinst_files/bd_axis_tanh.protoinst" -protoinst "protoinst_files/bd_dot.protoinst" -protoinst "protoinst_files/bd_layer.protoinst" -protoinst "protoinst_files/bd_bias_layer.protoinst" -protoinst "protoinst_files/bd_last_layer.protoinst" -log simulate.log
