#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.3 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Apr 27 18:29:16 PDT 2020
# SW Build 2405991 on Thu Dec  6 23:36:41 MST 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim tb_dot_behav -key {Behavioral:sim_dot:Functional:tb_dot} -tclbatch tb_dot.tcl -protoinst "protoinst_files/bd_c6eb.protoinst" -protoinst "protoinst_files/bd_5efb.protoinst" -protoinst "protoinst_files/bd_fpga.protoinst" -protoinst "protoinst_files/bd_axis_tanh.protoinst" -protoinst "protoinst_files/bd_dot.protoinst" -protoinst "protoinst_files/bd_layer.protoinst" -protoinst "protoinst_files/bd_bias_layer.protoinst" -view /home/lukefahr/e315/project_x/tb_dot_behav.wcfg -log simulate.log
